export {schools as default}

const schools = [
 {
   "Schools": "Alabama A & M University",
   "URL": "http://www.aamu.edu/Pages/default.aspx",
   "Majors": "Accounting, Applied Technology (MS), Art, Biology, Biology-Pre-Health, Biomedical Engineering, Chemistry, Clinical Mental Health Counseling (MS), Communications (Communications Studies/Journalism/Public Relations/Radio & Television/Recording Industry/Recording Technology), Computer Information Systems, Computer Science, Counselor Education (MS/MEd/EdS), Criminal Justice (Corrections/Criminology/Juvenile Justice/Law Enforcement), Dance, Early Childhood Education (MEd), Educational Leadership Policy & Law (EdD/PhD), Elementary Education (BS), English, Finance, Forensic Biology, Forensic Chemistry, Health Information Management, History, Interdisciplinary Studies, Instructional Leadership (EdS/MEd), Management, Marine Biology, Library Educational Media (EdS/MEd), Mathematics, Marketing, Music, Physical Education (BS), Political Science, Psychology, Recreational Therapy (BS), Rehabilitation Services, Secondary Education (Biology Education (BS/EdS/MEd)/Business/Marketing Education (BS)/ Chemistry Education (BS)/ Early Childhood Education (BS/EdS)/Elementary Education (EdS/MEd)/English Language Arts Education (BS/MEd)/ General Science Education (BS/MEd)/General Social Science (BS/EdS/MEd)/ Health Education (BS/MEd)/History (EdS)/ History Education (BS/MEd)/ Mathematics (EdS)/Mathematics Education (BS/MEd)/Music Education Choral (BME)/ Music Education, Instrumental (B.M.E.)/ Physical Education (MEd)), School Counseling (EdS), Social Work (BS), Special Education (BS/MR & LD/MEd), Teacher Education/P-12 Education (Reading Specialist (MEd)/ Music Ed Instrumental (MEd)/ Education: Physical Education (MEd)), Teacher Leadership (EdS), Theatre Arts,",
   "Degree": "Bachelor of Science,Masters of Science,Doctoral",
   "City": "Huntsville",
   "State": "Alabama",
   "Technology": "BLACKBOARD",
   "Financial Aid": "The AAMU Presidential Scholarship,The AAMU Merit Scholarship,The AAMU Transfer Merit Scholarship,Normalite Opportunity Scholarship,AAMU Heritage Gold,AAMU Heritage Silver,AAMU Heritage Bronze",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Bish",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Alabama State University",
   "URL": "http://www.alasu.edu/index.aspx",
   "Majors": "BS in Computer Information Systems, BS in Health Information Management,\n BS in Rehabilitation Services (concentration: addiction studies), BS in Biology (Marine Biology, Pre-Health Professional),BS in Chemistry (Forensic Science, Pre-Health Professional),BS in Computer Science,BS in Mathematics MS in Biology,MS in Forensic Science,MS Mathematics,Microbiology (Ph.D)",
   "Degree": "Bachelor of Science,Masters of Science,Doctoral",
   "City": "Montgomery",
   "State": "Alabama",
   "Technology": "Blackboard",
   "Financial Aid": "Presidential Academic, Academic Excellence, and Academic Incentive,BLACK AND GOLD SCHOLARSHIP,The Prince Winston Armstrong Scholarship,Arthur and Thelma Glass Scholarship,Charles S. Hill M.D. Scholarship,The Wallace Maryland, Jr. Scholarship,John Starks Scholarship,",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Bish",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Albany State University",
   "URL": "http://www.asurams.edu/",
   "Majors": "Associate of Science in Radiologic Science,Bachelor of Science in Nursing,Bachelor of Science with a Major in Biology, Bachelor of Science in Chemistry, Bachelor of Science in Computer Science,Master of Science in Nursing",
   "Degree": "Bachelor of Science (BS), Masters of Science (MS)",
   "City": "Albany",
   "State": "Georgia",
   "Technology": "D2L Brightspace",
   "Financial Aid": "Sabal Trail Transmission Scholarship,James M. Barnett Memorial Scholarship Fund,Ebuka Obiekwe Memorial Scholarship Fund,Wellington D. Swindall Book Scholarship",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Bish",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Alcorn State University",
   "URL": "http://www.alcorn.edu/",
   "Majors": "BS in degree in Computer Science,BS in degree in Mathematics and its concentration on Data Science,MS in degree in Computer and Information Science,",
   "Degree": "Bachelor of Science (BS), Masters of Science (MS)",
   "City": "Lorman",
   "State": "Mississippi",
   "Technology": "Blackboard",
   "Financial Aid": "L. T. AND REGINA ELLIS SCHOLARSHIP,DR. MALVIN A. WILLIAMS ENDOWED SCHOLARSHIP,THE DR. JESSE J. LUCAS SCHOLARSHIP FUND",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Bish",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Allen University",
   "URL": "http://allenuniversity.edu/",
   "Majors": "African American Studies,  Business Adminsitration, Criminial Justice, English, Mathematics, Military Science, Religion,",
   "Degree": "Bachelor of Art (BA), Bachelor of Science (BS), ",
   "City": "Columbia",
   "State": "South Carolina",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Bish",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Arkansas Baptist College",
   "URL": "http://www.arkansasbaptist.edu/",
   "Majors": "Accounting (AAB/BBA), Business Administration (BBA),  Christian Education (AA/BA), Criminal Justice (BA), Entrepreneurship (BBA),  Human Services (BA),  Religious Studies (AA/BA), Sports Management (BBA), Urban Community Leadership (AA/BA)",
   "Degree": "Bachelor of Business Administration, Associate of Arts in Business Administration",
   "City": "Little Rock",
   "State": "Arkansas",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Bish",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Benedict College",
   "URL": "http://www.benedict.edu/",
   "Majors": "Cybersecurity (BS), Computer Engineering(BS), Mathematics (BS), Chemistry (BS),  Computer Science (BS), Enviromental Engineering (BS),",
   "Degree": "Bachelor of Science (BS), ",
   "City": "Columbia",
   "State": "South Carolina",
   "Technology": "edvance360",
   "Financial Aid": "LIFE Scholarship, Palmetto Fellows Scholarhip Program, HOPE Scholarship",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Bish",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Bennett College for Women",
   "URL": "http://www.bennett.edu/",
   "Majors": "BS in Chemistry, BS in Computer Science, BS in Mathematics",
   "Degree": "Bachelor of Science (BS), ",
   "City": "Columbia",
   "State": "South Carolina",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Bish",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Bethune-Cookman University",
   "URL": "http://www.cookman.edu/",
   "Majors": "Biology, Chemistry (BS), BioChemistry (BS), Computer Engineering (BS), Computer Information Systems (BS), Computer Science (BS), Mathematics (BS)",
   "Degree": "Bachelor of Science (BS), ",
   "City": "Daytona Beach",
   "State": "Florida",
   "Technology": "Canvas",
   "Financial Aid": "Gaming Scholarship Program, \"Careers in Coding” Contest, BrainBuxa Scholarship, Molded Dimensions,",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Bish",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Bishop State Community College",
   "URL": "https://www.bishop.edu/",
   "Majors": "Cosmetology (CT), Diesel Technology (CT), Nursing (AAS), ",
   "Degree": "Associate in Arts (AA), Associate in Science (AS), Career Technical (CT), ",
   "City": "Mobile",
   "State": "Alabama",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Bish",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Bluefield State College",
   "URL": "https://www.bluefieldstate.edu/",
   "Majors": "Accountancy (BS), Business Administration (BS), Civil Engineering Technology (AS, BS), Computer Science (BS), Criminal Justice Administration (BS), Cybersecurity (M), Early & Middle School Education (BS), Electrical Engineering Technology (AS, BS), Engineering Management (BS),  Entrepreneurship (BS), Health Services Management (BS), Mechanical Engineering (AS, BS), Nursing (BA, AS), Radiologic Technology (AS),",
   "Degree": "Associate of Science, Bachelor of Science, Minor,",
   "City": "Bluefield",
   "State": "West Virginia",
   "Technology": "Moodle",
   "Financial Aid": "Almeta H. Martin Endowed Scholarship, Benjamin H. Martin Endowed Scholarship, BOG Auxiliary, BOG Tuition Employee Dependent, BOG Tuition Waiver Academic, BOG Tuition Waiver Athletic, BOG Tuition Waiver Foster Care, BOG Tuition Waiver Mil Depend, Carl P. and Selba Meadows Boyd Scholarship, Broady Family Scholarship, Morgan C. Campbell Scholarship, Cardwell Family Endowed Scholarship, Carter Family Foundation, Cole Harley-Davidson Scholarship, CONSOL Energy Scholarship in Engineering Technology, Stelio and Betty Tracy Corte Endowed Scholarship, Craddock Scholarship Award, Credit Bureau of the Virginias, Douglas F. Crickmer Memorial Scholarship, Dalton Family Scholarship, Brian A. Delp Humanitarian Athletic Scholarship, Brian A. Delp Service Award, Thomas and Charlotte Deskins Scholarship, Dorothy Ann Surface Endowed Scholarship, GED scholarship, George Joseph Featherstone II Annual Scholarship, Bluefield State Foundation Scholarship, Fred Gilbert Endowed Scholarship, Grants Supermarket Endowed Scholarship, Hamilton Hatter Alumni Endowed Scholarship, Frank Hart Endowed Scholarship in Engineering Technology, William S. Height Scholarship, Health Science Waiver, Tom Joyner Scholarship, Prema Natarajan Krishnan Scholarship in Nursing, Krotseng Annual Scholarship, Krotseng Go For Graduation, Lawson Scholarship, Central Area of the Links Inc. Scholarship, Rhonda Grace Linkous Endowed Scholarship, John and Elisabeth MacClarence Scholarship, Massey Scholarship, McConnell Family Scholarship, Martha and Mark Oblinger Scholarship, Billy G. Moore Scholarship, Dr. Patricia A. MULVEY Scholarship, Nannie Pearl Walls Endowed Scholarship, Neighborhood Investment Scholarships, W. Paul Cole Jr. Leadership Scholarship, Pocahontas Electrical and Mining Scholarship, Roy Pruett Jr. Scholarship for Electrical Engineers, John J. & Sheila Belcher Rinehart, Akhtar Safder Scholarship, June Oblinger Shott Scholarship, Greg Shrewsberry Memorial Scholarship, Taylor Family Scholarship, MacClarence Teacher Testing Scholarship, Luther and Mary Ida Vandross Scholarship, Bartlett – Welcker Scholarship, Wellington-Swindall, Mae Jerolee White Scholarship, West Virginia Society of Washington DC Book Scholarship,",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Nich",
   "Virtual Tour": "https://tour.bluefieldstate.edu/",
   "Graduates": "",
   "Notes": "black enrollment?"
 },
 {
   "Schools": "Bowie State University",
   "URL": "https://www.bowiestate.edu/",
   "Majors": "Addictions Counseling (Certificate), Applied & Computational Mathematics (MS, Certificate), Bioinformatics (BS), Biology (BS), Business Administration (BA, MBA), Chemistry (BS), Child & Adolescent Studies (BS), Communications (BA), Computer Science (BS, MS, Doctorate of Science), Computer Technology (BS), Counseling Psychology (MA), Culturally Responsive Teacher Leadership (M.Ed), Criminal Justice (BS), Database Management/Artificial Intelligence (Certificate), Early Childhood Education (BA), Educational Leadership (Ed.D), Elementary Education (BA, M.Ed), Elementary & Secondary School Administration (M.Ed), English (BA, MA), Fine Arts (BA), Geographical Information Systems & Image Processing (Certificate),  Graphics & User Interface (Certificate), History & Government (BA), Human Resource Development (MA), Information Syatems Analyst (Certificate), Management Information Systems (MS), Mathematics (BS), Mental Health (MA), Networks & Distributed Systems (Certificate), Nursing (BS, MSN), Organizational Communications (MA, Certificate), Project Management (Certificate),  Psychology (BA), Psychotherapy (Certificate), Public Administration (MPA, Certificate), Reading Education (M.Ed), Science Education (BA), Scientific Software Development (Certificate), School Counseling (M.Ed), School Psychology (MA, Certificate), Secondary Education (M.Ed), Social Justice (BA), Social Work (BA), Sociology(BA), Software Engineering (Certificate), Special Education (BA, M.Ed), Sport Management (BS), Teaching (MAT), Theatre Arts (BA), Visual Communication & Digital Media Arts (BA), ",
   "Degree": "Bachelor of Arts, Bachelor of Science, Masters of Arts, Certificate",
   "City": "Bowie",
   "State": "Maryland",
   "Technology": "Dual Enrollment,",
   "Financial Aid": "Academic Scholarship, Band Scholarship, BSU National Alumni Association, BSU Associate of Arts in Teaching, Conroy Scholarship, First Generation College Student Scholarship, Golden Flame Scholarship, Richard W. Collins III Leadership with Honor Scholarship, TEACH grant, Work Study,",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Nich",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Central State University",
   "URL": "http://www.centralstate.edu/index.php",
   "Majors": "Accounting (BS), Africana Studies (BA), Agricultural Education (BS), Business Administration (BA, BS), Computer Science (BS), Criminal Justice (BA), Early Childhood Education (BA), English (BA), Environmental Engineering (BS), Exercise Science (BS), Food Science (BS), Graphic Design (BA), Gerontology (BA), History (BA), International Languages and Literatures (BA), Industrial Technology (BS), Integrated Language Arts Education (BA), Integrated Language Mathematics Education (BA), Integrated Language Social Studies Education (BA), Intervention Specialist (BA), Jazz Studies (BA), Journalism and Mass Communication (BA), Life Science Education (BA), Manufacturing Engineering (BS), Mathematics (BS), Middle Childhood Education (BA), Philosophy and Religion (BA), Physical Science Education (BA), Political Science (BA), Psychology (BA), Recreation (BA), Sociology (BA), Social Work (BA), Studio Art (BA), Sustainable Agriculture (BS), Music Education (BA), Music Performance (BA), Theatre (BA), Water Resources Management (BS),",
   "Degree": "Bachelor of Art (BA), Bachelor of Science (BS), ",
   "City": "Wilberforce",
   "State": "Ohio",
   "Technology": "Hype",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Nich",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Cheyney University of Pennsylvania",
   "URL": "http://www.cheyney.edu/",
   "Majors": "Biology (BS), Business Administration (BS), Computer & Information Science (BS), Communications (BA), Early Childhood Education (BS), Early Childhood and Special Education (BS), English (BA), Fine Arts (BA), Graphic Design (BS), Hotel, Restaurant and Tourism Management (BS), Liberal Studies (BA), Mathematics (BS), Psychology (BA), Recreation and Leisure Management (BS), Social Relations (BA),",
   "Degree": "Bachelor of Art (BA), Bachelor of Science (BS), ",
   "City": "Cheyney",
   "State": "Pennsylvania",
   "Technology": "Gen Ed",
   "Financial Aid": "State Scholarship Waivers, TEACH Grant, Work Study,",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Nich",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Claflin University",
   "URL": "http://www.claflin.edu/",
   "Majors": "African and African-American Studies (BA), Art Education (BA), Biochemistry (BS), Bioinformatics (BS), Biology (BS), Biotechnology (BS, MS), Business Administration (BS, MBA, O-MBA), Chemistry (BS), Computer Engineering (BS), Computer Science (BS), Criminal Justice (BA, O-BA, MS), Curriculum & Instruction (M.Ed, O-M.Ed), Digital Design (BA), Early Childhood Education (BS), Elementary Education (BS), English (BA), English Education (BA), Environmental Science (BS), Foreign Language (BA), Human Performance and Recreation (BS), Management (BS), Management Information Science (BS), Marketing (BS), Mass Communication (BA), Mathematics (BS), Mathematics Education (BS), Middle Level Education (BS), Music (BA), Music Education (BA), Nursing (BS, O-BS), Organizational Management (BS, O-BS), Philosophy & Religion (BA), PK-12 and Secondary Education (BS), Political Science (BA), Psychology (BA, O-BA), Sociology (BA), Sport Management (BS), Studio Art (BA),",
   "Degree": "Bachelor of Art (BA), Bachelor of Science (BS), Online – BA, Master of Business (MBA), Masters of Education (M.Ed), Masters of Science (MS), Online – BS, Online – MBA, Online – M.Ed,",
   "City": "Orangeburg",
   "State": "South Carolina",
   "Technology": "Moodle",
   "Financial Aid": "Work-Study, Veterans' Assistance",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Nich",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Clark Atlanta University",
   "URL": "http://www.cau.edu/",
   "Majors": "Accounting (BA, MA), Africana Women's Studies (BA, MA, PhD), African American Studies (BA, MA, PhD), Art (BA), Art History (BA, MA), Biology (BA, MA, PhD), Business Administration (BA, MBA), Chemistry (BS), Clinical Mental Health (MA), Computer and Information Systems (BA, MA), Computer Science (BS), Counseling (BA),Cyber-Physical Systems (BS, MS, BS/MS) Cybersecurity (BA, MA), Criminal Justice (BS), Early Childhood Education (MA, Ed.S, Ed.D), Economics (BA, MA), Educational Leadership (BA), Educational Studies (MA), Engineering/Dual Degree (BA, MA, PhD), English (BA), Fashion Design and Merchandising (BA), History (BA, MA, PhD), Industrial Chemistry (BA, MA), Mass Media Arts (MA), Mathematics (BA, MA), Music (BA, MA, PhD), Philosophy (BA), Physics (BA, MPA), Political Science (BA), Psychology (BA, MA), Public Administration (BA), Religion (BA), School Counseling (MAT), Secondary Education Math (MA), Secondary Education Science (MAT), Social Work (BSW, MSW, PhD), Sociology (BA), Speech Communication (BA), Special Education (MA), Theatre Arts (BA),",
   "Degree": "Bachelor of Art (BA), Bachelor of Science (BS), Bachelor in Social Work (BSW), Doctor of Philosophy (Ph.D), Master of Business (MBA), Masters of Science (MS), Masters of Art (MA), Masters of Arts in Teaching (MAT), Master in Social Work (MSW), Specialist (Ed.S),",
   "City": "Atlanta",
   "State": "Georgia",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Nich",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Clinton Junior College",
   "URL": "https://www.clintoncollege.edu/",
   "Majors": "Business Administration (AS, BS), Early Childhood Development (AA), Liberal Arts (AA), Religious Studies (AA, BA), Biology (BS), Natural Sciences (AS), ",
   "Degree": "Associate of Arts (AA), Associate of Science (AS), Bachelor of Art (BA),",
   "City": "Rock Hill",
   "State": "South Carolina",
   "Technology": "",
   "Financial Aid": "Veterans, Work Study",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Nich",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Coahoma Community College",
   "URL": "http://www.coahomacc.edu/",
   "Majors": "Accounting Technology (AA, CC, CT), Automotive Technology (AS), Barber (AA, CC), Brick, Block, and Stone Masonry (AA), Carpentry (AA, CT), Collision Repair Technology (AA), Computer Servicing Technology (CT), Cosmetology (AA, CC), Culinary Arts (AA), Early Childhood Education Technology (AA), Health-care Data Technology Medical Billing and Coding (AA, CC, CT), Hotel and Restaurant Management Technology (AA), Industrial Maintenance Technology (AA), Office Systems Technology (AA, CC, CT), Welding and Cutting Technology (AA),",
   "Degree": "Associate of Science (AS), Career Certificate (CC), Certificate of Technical (CT), ",
   "City": "Clarkdale",
   "State": "Mississippi",
   "Technology": "Canvas, Dual Enrollment",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Nich",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Concordia College-Selma",
   "URL": "http://www.concordiaselma.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Selma",
   "State": "Alabama",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Nich",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Coppin State University",
   "URL": "https://www.coppin.edu/",
   "Majors": "Accounting (BS), Adult & Continuing Education (MS), Alcohol and Substance Abuse Counseling (MS), Applied Psychology (BS), Biology (BS), Chemistry (BS), Computer Science (BS), Contemporary Educational Leadership (M.Ed), Criminal Justice (BS), Criminal Justice and Law Enforcement (MS), Curriculum and Instruction (M.Ed), Dance (BS), Early Childhood Child Care (BS), Early Childhood Human Development (BS), Elementary Education (BS), English (BA), Forensic Investigation (Certificate), Global Studies (BA), Health Information Management (BS), Health Sciences (BS), History (BS), Histo-technology (BS), Human Services Administration (MS), Interdisciplinary Studies (BS), Investigative Sciences (Certificate), Management (BS), Management and Marketing (O-BS), Management Information Systems (BS), Marketing (BS), Mathematics (BS), Nonprofit Leadership (BS), Nursing (BS, BSA, MS, DNP), Political Science (BS), Reading (MS), Rehabilitation Counseling (M.Ed), Rehabilitation Services (BS), Social Science (BS), Social Work (BS), Special Education (BS, M.Ed), Sport Management (BS), Teaching (MA), Urban Arts (BS), Urban Studies (BS),",
   "Degree": "Bachelor of Science (BS), BS Accelerated (BSA), Doctor of Nursing Practice (DNP), Masters of Art (MA), Masters Masters of Education (M.Ed), Masters of Science (MS), Online – BS,  ",
   "City": "Baltimore",
   "State": "Maryland",
   "Technology": "Pearson Learning Solutions, Skype, Lync, Blackboard, Tegrity",
   "Financial Aid": "Alumni Association Scholarship, Athletic Scholarships, Delores E. Hunter Endowed Scholarship Fund, Honors, India Continental, Maxie Collier Program, Merit Awards, Nursing Awards, Private Scholarships, ROTC, Rehabilitation Services Administration, Senior Opportunity Scholarship (SOS), TEACH, Veterans, Work Study",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Nich",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Delaware State University",
   "URL": "https://www.desu.edu/",
   "Majors": "Accounting (BS), Africana Studies (BS), Agriculture: Agri-Business (BS), Agriculture: Agriscience Education (BS), Agriculture: Animal Science (BS), Agriculture: Animal Science (MS), Agriculture: Equine Business Management (BS), Agriculture: General Agriculture (BS), Agriculture Plant Science (MS), Agriculture: Plant Science: Agronomy (BS), Agriculture: Plant Science: Horticulture (BS), Agriculture: Pre-Veterinary Science (BS), Applied Chemistry (MS), Applied Optics (MS), Art Education (BA), Aviation: Aviation Management (BS), Aviation Professional Pilot (BS), Biological Sciences (MS), Biological Sciences: Bioinformatics (BS), Biological Sciences: General Biology (BS), Biological Sciences: Health Professions (BS), Biological Sciences: Research Professions (BS), Business Administration: Business Analytics (MBA), Business Administration: CPA (MBA), Business Administration: Finance (MBA), Business Administration: Information Systems (MBA), Chemistry (BS), Chemistry for Health Professionals (BS), Computer Science (BS), Computer Science (MS), Criminal Justice (BA), Dual-Title MA TESOL/Bilingual Education and M. Ed. in Educational Leadership (M.Ed.), Early Childhood Education (Birth-2) (BS), Educational Leadership (M.Ed.), Educational Leadership: Higher Education (Ed.D.), Educational Leadership: K-12 (Ed.D), Elementary Education (K-6), Engineering Physics: Bioengineering (BS), Engineering Physics: Optical Engineering (BS), English (BA), Finance: Financial Economics (BS), Food and Nutritional Sciences: Didactic Program in Dietetics (BS), Food and Nutritional Sciences: Food Science (BS), Food and Nutritional Sciences: Nutritional Science (BS), Food and Nutritional Sciences: Pre-Allied Health Sciences (BS), Food and Nutritional Sciences: Pre-Medicine and Pre-Physician Assistant (BS), Food Science and Biotechnology: Biotechnology (MS), Food Science and Biotechnology: Food Chemistry (MS), Food Science and Biotechnology: Food Microbiology (MS), Forensic Biology (BS), History (BA), Hospitality and Tourism Management: Casino Management (BS), Information Technology (BS), Integrated Studies (BS), Kinesiology (BS), Management: Business Analytics (BS), Management: General Management (BS), Management: Human Resource Management (BS), Management: Management Information Systems/ERP (BA), Management: Marketing (BS), Mass Communication: Convergence Journalism (BA), Mass Communication: Digital Media Arts (BA), Mass Communication: Public Relations & Advertising (BA), Mathematics Education (BS), Mathematics, Applied (MS), Mathematics, Pure (MS), Mathematics: Data Analytics (BS), Middle Level Education (6-8) (BS), Molecular and Cellular Neuroscience (MS), Music Education: Instrumental (BA), Music Education: Vocal (BA), Music Industry (BA), Music Instrumental (BA), Music Vocal (BA), Natural Resources (MS), Natural Resources: Environmental Science (BS), Natural Resources: Fisheries Management (BS), Natural Resources: Wildlife Management (BS), Neuroscience (PhD), New Media in Art (BA), Nursing (BA), Nursing, MSN: Global Leadership (MSN), Nursing, MSN: Nursing Education (MSN), Optics (PhD), Physical Education (BS), Physics, BS (BS), Physics MS (MS), Political Science (BA), Psychology (BS), Public Administration (MPA), Public Health (BS), Social Work, BSW (BSW), Social Work, MSW (MSW), Sociology (BA), Sport Administration (MSA), Sport Management (BS), Studio Art (BA), TESOL (Teaching English to Speakers of Other Languages/Bilingual Education) (MA), Textile and Apparel Studies: Fashion Merchandising (BS)",
   "Degree": "",
   "City": "Dover",
   "State": "Delaware",
   "Technology": "Pearson Learning Solutions",
   "Financial Aid": "Inspire Scholarship, DSU GAP, Visual & Performing Arts, Academic Partial & Full",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Denmark Technical College",
   "URL": "http://www.denmarktech.edu/",
   "Majors": "Administrative Office Technology (AAS), Computer Technology (AAS), Criminal Justice Technology (AAS), Early Care & Education (AAS), Electromechanical Engineering Technology (AAS), Business Administration (AAS), General Technology (AAS), Human Services (AAS), Administrative Support (Diploma In Applied Science), Barbering (Diploma In Applied Science), Cosmetology (Diploma In Applied Science), Practical Nursing (Diploma In Applied Science), Accounting (Certificate In Applied Science), Building Construction Fundamentals (Certificate In Applied Science), Computer Servicing & Repair (Certificate In Applied Science), Criminal Justice (Certificate In Applied Science), Culinary Arts (Certificate In Applied Science), Cybersecurity (Certificate In Applied Science), Early Childhood Development (Certificate In Applied Science), Entrepreneurship/Small Business Management (Certificate in Applied Science), General Studies (Certificate In Applied Science), Nurse Aide Assistant (Certificate In Applied Science), Plumbing (Certificate In Applied Science), Pre-Medical (Certificate In Applied Science), Welding (Certificate In Applied Science), Word Processing (Certificate In Applied Science),\n",
   "Degree": "",
   "City": "Denmark",
   "State": "South Carolina",
   "Technology": "SCTechConnect\n",
   "Financial Aid": "STEM Scholarships, Presidential Scholarships, Vice-Presidential Scholarships, Deans Scholarships, ZipRecruiter Scholarships",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Dillard University",
   "URL": "http://www.dillard.edu/",
   "Majors": "English (BA), Film (BA), Food Studies (minor), Mass Communication (BA), Music (BA), Theatre Arts (BA), Visual Arts (BA), Public Health (BS), Biology (BS), Chemistry (BA/BS), Computer Science (BS), Mathematics and Actuarial Science (BS), Physics (BS), Criminal Justice (BA), Political Science (BA), Psychology (BA), Social Work (BA), Urban Studies and Public Policy (BS), Accounting (BS), Financial Economics (BS), Business Administration (BS), Nursing (RN to BSN) Nursing (LPN to BSN)",
   "Degree": " BA BS BSN",
   "City": "New Orleans",
   "State": "Louisiana",
   "Technology": "BLEU4ed  MERLOT OLC USDLA",
   "Financial Aid": "All Outside Scholarships use: www.aie.org/coaching",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Edward Waters College",
   "URL": "https://www.ewc.edu/",
   "Majors": "Biology (BS) Business Administration (BBA) Criminal Justice (BA) Communications (BS) Psychology (BA)",
   "Degree": "BA BBA BS",
   "City": "Jacksonville",
   "State": "Florida",
   "Technology": "N/A",
   "Financial Aid": "INSTITUTIONAL SCHOLARSHIPS: Honors Scholarship  Merit Scholarship  Transfer Scholarship  Freshman Grant  Talent-Based Scholarship  Athletic Scholarship\n\n",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Elizabeth City State University",
   "URL": "http://www.ecsu.edu/",
   "Majors": "Computer Science (BS)  Criminal Justice (BS)  Emergency Management (BS)  Engineering Technology (BS)  English (BA)  History (BA)  Interdisciplinary Studies (BA)   Mathematics (BS) Music (BA)  Social Work (BSW)  Sociology (BA) Mathematics Education (MS)  Applied Mathematics (MS)  Community College Teaching (MS)  Remote Sensing (MS) \n\n",
   "Degree": "BA  BS  BSW  MS",
   "City": "Elizabeth City",
   "State": "North Carolina",
   "Technology": "Blackboard  Echo360 ",
   "Financial Aid": "Chancellor’s Academic Scholarship UNC Campus Based Scholarship  Federal Work Study \n",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Fayetteville State University",
   "URL": "https://www.uncfsu.edu/",
   "Majors": "Accounting (BS) Accounting Risk Management and Insurance Concentration (BS) Banking and Finance (BS) Biology Biotechnology and Molecular Biology Concentration (BS) Biology Organismal Biology Concentration (BS) Biology Plant Sciences Concentration (BS) Birth through Kindergarten Non-Teaching (BS) Business Administration Entrepreneurship Concentration (BS) Business Administration General Business Concentration (BS) Business Administration Healthcare (BS) Business Administration Management Concentration (BS) Business Administration Information Systems Business Analytics (BS) Business Administration Marketing (BS) Chemistry with a concentration in Biochemistry (BS) Chemistry with a concentration in Chemistry Entrepreneurship (BS) Chemistry with a concentration in General Chemistry (BS) Chemistry with a concentration in Pre-Health (BS) Chemistry with a concentration in Materials Science (BS) Chemistry with a concentration in Pre-Health (BS) Chemistry with a concentration in Pre-Pharmacy (BS) Communication (BA) Computer Science (BS) Criminal Justice (BS) Elementary Education Core Academic Studies Concentration (BS) Elementary Education English Concentration (BS) Elementary Education Health Concentration (BS) Elementary Education History Concentration Elementary Education Mathematics (BS) Elementary Education Psychology Concentration (BS) Elementary Education Reading Concentration (BS) Elementary Education Sociology Concentration (BS) Elementary Education Spanish Concentration (BS) Elementary Education Special Education Concentration (BS) Elementary Education Teaching English as a Second Language Concentration (BS) English Language and Literature (BA) English  Language and Literature Creative and Professional Writing Concentration (BA) English Language and Literature Pre-Law Concentration (BA) English Language and Literature Teaching License Concentration (BS) Fire and Emergency Services Administration (BS) Forensic Science Biology Concentration (BS) Health and Physical Education (BS) Health and Physical Education Non-Teaching Community Health (BS) Health and Physical Education Non-Teaching Sports Management (BS):  Healthcare Administration (BS) Healthcare Administration Risk Management and Insurance (BS) History (BA) Information Systems and Business Analytics (BS) Intelligence Studies (BA) Mathematics (BS) Mathematics Teaching Licensure Concentration (Secondary Education 9-12) (BS) Middle Grades Education Language Arts Concentration (BS) Middle Grades Education Mathematics Concentration (BS) Middle Grades Education Science Concentration (BS) Middle Grades Education Social Studies Concentration (BS) Music Instrumental Studies Concentration (BA) Music Video Studies Concentration (BA) Nursing Generic Four Year Track (BS) Nursing RN to BSN Track (BS) Political Science (BA) Political Science Environmental Politics and Policy (BA) Political Science Public Administration (BA) Professional Studies (BA) Psychology (BS) Social Work (BSW) Sociology (BA) Spanish (BA) Spanish Teaching (BS) Theatre (BA) Visual Arts Digital Art Concentration (BA) Visual Arts, Studio Art Concentration (BA)",
   "Degree": "BA  BS  BSN  BSW  ",
   "City": "Fayetteville",
   "State": "North Carolina",
   "Technology": "Canvas  Upswing  Respondus  Zoom  Microsoft Teams ",
   "Financial Aid": "Chancellor’s Special Talent Scholarship  Dr. Valeria Fleming STEM Scholarship\n",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Fisk University",
   "URL": "https://www.fisk.edu/",
   "Majors": "Art (BS) Biology (BA/MA) Biochemistry and Molecular Biology (BS) Business Administration (BS) Chemistry (BS) Computer Science (BS) English (BA) History (BA) Mathematics (BA) Music - Music Education (BA/BS/BM) Physics (BA/BS/MA) Political Science (BA) Psychology (BA/MA) Sociology (BA) Spanish (BA) Special Education (BA))",
   "Degree": "BA  BS  BSN  BSW  \n",
   "City": "Nashville",
   "State": "Tennessee",
   "Technology": "MERLOT  OPENSTAX  ",
   "Financial Aid": "Erastus Milo Cravath Presidential Scholarship  Fisk Outstanding Scholars & Leaders Award  Ella Sheperd Moore Provost Scholarship   Fisk Award for Music Majors  Fisk University Athletic Scholarship \n",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Florida Agricultural and Mechanical University",
   "URL": "http://www.famu.edu/",
   "Majors": "Agribusiness (BS) Agronomy (BS) Animal Science (BS) Biological and Agricultural System Engineering (BS) Entomology (BS) Food Science (BS) Forestry and Natural Resources Conservation (BS) Veterinary (BS) Biology Education (BS) Chemistry Education (BS) Elementary Education (BS) Mathematics Education (BS)Music Education (BS) Physical Education (BS) Physics Education (BS) Pre-Kindergarten/Primary Education (BS) Social Science Teacher Education (BS) Technology Education (BS) Pharmaceutical Sciences (BS) Biology (Pre-Professional/Molecular-Cell) (BS) Chemistry (ACS/Biochemistry/Pre-Medicine/Dentistry) (BS) Computer Information Systems (BS) Computer Science (BS) Mathematics (Mathematical Sciences/Traditional/Actuarial Sciences) (BS) Physics (General/Applied) (BS) Arts in African-American Studies (BA/BS) Criminal Justice (BS) English (BA) Fine Arts (BA/BS) History (BA/BS) Music (BA/BS) Philosophy and Religion (BA/BS) Psychology (BA/BS) Social Work (BA/BS) Sociology (BS) Arts in Theatre (BA/BS) Cardiopulmonary Sciences (BS) Health Care Management (BS) Health Information Management (BS) Health Sciences (BS) Architecture (BS) Architectural Studies (BS) Construction Engineering Technology (BS) Electronic Engineering Technology (BS) Accounting (BS) Business Administration (BS) Business Administration with a Program Major in Facilities Management (BS) Economics with Minor in Business (BS) Environmental Sciences (BS) Graphic Design (BS) Journalism (BS) Public Relations (BS) Nursing (BS)  Community Psychology (MS)  Social Work (MSW)  Political Science (MASS)  Public Administration (MASS)  History (MASS)  Criminal Justice (MASS)  Global Security and International Affairs (MASS)  Computer Information Science (MS)  Software Engineering Science (MS)  Molecular Cellular Biology (MS)  Ecology (MS)  Physiology (MS)  Biological Sciences - Non Thesis Track (MS)  Chemistry (MS)  Physics (MS)  Physics (PhD)  Sport Management (MS)  Educational Leadership (MS/MEd)  Counselor Education (MS/MEd)  Curriculum and Instruction MEd)  Educational Leadership (PhD)  Business Administration (online) (MBA)  Business Administration (MBA/MS)  Pharm-D/MBA (PharmD)  Pharmaceutical Sciences (MS)  Pharmaceutical Sciences (PhD)  Specialization in Health Outcomes Research and Pharmacoeconomics (PhD)  Public Health (MPH)   Public Health Online (MPH)  Public Health (DrPH)  Health Administration (MHA)  Occupational Therapy (MSOT)  Physical Therapy (DPT)  Nursing (MSN)  Nursing (online) (MSN)  Environmental Science (MS)  Environmental Science (PhD)  Agribusiness (MS)  Entomology (MS)  Plant Science (MS)  Agricultural Science (non-thesis) (MS)  Agricultural Science (thesis) (MS)  Soil and Water (MS)  Entomology (PhD)   Architecture (MS)  Architecture (MArch)  Biomedical Engineering (MS)  Biomedical Engineering (PhD)  Chemical Engineering (MS)  Chemical Engineering (PhD)  Civil Engineering (MS/MEng)  Civil Engineering (PhD)  Electrical Engineering (MS)  Electrical Engineering (PhD)  Mechanical Engineering (MS)  Mechanical Engineering (PhD)  Industrial Engineering (MS)  Industrial Engineering (PhD)\n",
   "Degree": "BA  BS  MA  MArch  MBA  MEd   MEng  MHA   MS  MSOT  MSN   MSW  MASS  MPH  PhD  PharmD  DrPH      \n",
   "City": "Tallahassee",
   "State": "Florida",
   "Technology": "Respondus  Blackboard\n",
   "Financial Aid": "Adopted High School Scholarship  Distinguished Scholars Award Scholarship  Elizabeth Benacquisto Merit Incentive Scholarship  George W. Gore Award  Presidential Special Scholarship\n\n",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Florida Memorial University",
   "URL": "http://www.fmuniv.edu/",
   "Majors": "Aviation Management (BS)  Aeronautical Science (BS)   Biology (BS)  Business Administration (BS)  Cybersecurity (BS)  Computer Science (BS)  Information Systems (BS)  Mathematics (BS)  Biology (BS)  Chemistry (BS)  Environmental Science (BS)   Communication (BA)  English (BA) : Religion and Philosophy (BA)  Physics (BS)  Music (BA)  Music and Entertainment Public Relations (BA)  Criminal Justice (BA)  Law and Government (BA)  Psychology (BA)  Bachelor of Social Work (BSW)  Sociology (BA)  Accounting (BS)  Business Administration (BS)  Finance (BS)  Marketing (BS)   Combined Elementary Education ESOL (K-6) and Exceptional Education ESOL (K-12)/ESOL (BS)  Secondary Education: English / ESOL (6-12) (BS)  Secondary Education: Mathematics (6-12) (BS)   Secondary Education: Social Science (6-12) (BS)  Business Administration (MBA)  Exceptional Education/ESOL  (MEd)   Reading (MEd)\n",
   "Degree": "BA  BS : MBA  MEd\n",
   "City": "Miami Gardens",
   "State": "Florida",
   "Technology": "Blackboard  Citrix \n",
   "Financial Aid": "Freshman Scholarships  UNCF Scholarships  A.B. Coleman Endowed Scholarships  ",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Fort Valley State University",
   "URL": "http://www.fvsu.edu/",
   "Majors": "Biology (BS) Biotechnology (MS) Chemistry (BS) Electronics Engineering Technology (BS) Engineering Technology (BS) Mathematics (BS) Physics (BS)",
   "Degree": "Bachelor of Science (BS) Career Certificate (CC)",
   "City": "Fort Valley",
   "State": "Georgia",
   "Technology": "Baner WebX Zoom",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Gadsden State Community College",
   "URL": "http://www.gadsdenstate.edu/",
   "Majors": "Accounting Specialist (Computerized) (CC) Accounting Technology (AAS) Air Conditioning and Refrigeration (AAS) Auto Collision Repair (TC) Automotive Manufacturing Technology (AAS) Automotive Service (TC) Child Development (AAS, CC) Civil Engineering Technology (AAS) Construction Technology (AC) Computer Science Technology (AAS, CC) Court Reporting Technology (AAS) Diagnostic Medical Sonography (CC) Diesel Technology (CC) Electronic Engineering Technology (AAS, CC) Engineering Design Technology (AAS) Electrical Technology (AAS) Emergency Medical Services (CC) Fine Arts (AA) General Studies (AS) Health Information Technology Management (CC) Health, PE, Recreation (AS) Human Services (AAS) Liberal Arts (AA) Industrial Automation Technology (AAS) Marketing Management (AAS) Massage Therapy (CC) Mechanical Design Technology (AAS, TC) Medical Coding/Billing Specialist (CC) Medical Laboratory Technology (CC) Office Administration (AAS) Nursing (CC) Paralegal Studies (AAS) Precision Machining (AAS, CC, CT) Phlebotomy Training (CC) Radiologic Technology (CC) Salon and Spa Management (AAS, AC, CC) Surgical Operating Room Technician (CC) Welding Technology (AC, CC) Word Processing Specialist (CC)",
   "Degree": "Advance Short-Term Certificate (AC) Associate of Applied Science (AAS) Associate of Arts (AA) Associate of Science (AS) Career Certificate (CC) Technology Certificate (TC)",
   "City": "Gadsden",
   "State": "Alabama",
   "Technology": "",
   "Financial Aid": "Vetern",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Nich",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": "1 Black person on homepage"
 },
 {
   "Schools": "Grambling State University",
   "URL": "http://www.gram.edu/",
   "Majors": "Accounting (BS) Biology (BS, DC) Chemistry (BS) Chile Development & Early Litature (BS) Cloud Computing (BS) Computer Information Systems (BS) Computer Science (BS) Curriculum & Instruction (MEd) Criminal Justice (BS, MS) Cybersecurity (BS) Development Education (MS, PMC, EdD) Elementary Education (BS, MAT) Engineering Technology (BS) English (BA) Family Nurse Practitioner (PMC) History (BA) Kinesiology (BS) Leisure Studies (BS) Management (BS) Marketing (BS) Mass Communication (BA, MA) Mathematics (BS) Music (BA) Nursing (BSN) Physics (BS) Psychology (BA) Public Administration (MPA) Secondary Education for Middle School (BS, MAT) Social Science (MA) Social Work (BSW, MSW) Sociology (BA) Special Education (BS) Sports Administration (MS) Visual and Performing Arts (BA)",
   "Degree": "Bachelor of Art (BA) Bachelor of Science (BS) Bachelor in Nursing (BSN) Bachelor in Social Work (BSW) Doctor of Chiropractic (DC) Educational Doctorate (EdD) Masters of Art (MA) Masters of Education (MEd) Masters of Arts in Teaching (MAT) Masters in Public Administration (MPA) Masters of Science (MS) Master in Social Work (MSW) Post-Masters Certificate (PMC)",
   "City": "Grambling",
   "State": "Louisiana",
   "Technology": "Banner Canvas Distance Learning",
   "Financial Aid": "100 Horses Alumni Band Scholarship Abdulalim A. Shabazz Non-Endowed Scholarship Alexis Johnson Scholarship Bernadene Coleman-Pope Scholarship Bryan C. Griffin Endowed Scholarship for Math and Computer Science Charles E. Grier Non-Endowed Spirit Award Charlotte & Harold Mouton Non-Endowed Scholarship Charlotte & Harold Mouton Non-Endowed Scholarship Crescent City Chapter Scholarship Debbie N. Robinson Endowed Scholarship in the College of Business The Earline Jones McCain Educational Non-Endowed Scholarship James Jackson Delta Sigma Chapter/Alpha Phi Alpha Fraternity, Inc. Non Endowed Scholarship Jennie V. Wilson Scholarship Fund Dr. Jimmy McJamerson Non-Endowed Scholarship John L. and Evelyn Ford Crayton Non-Endowed Student Scholarship Laura B. Spencer GAP Scholarship Lulla Emmanuel Wiltz Non-Endowed Memorial Scholarship Fund McCray-Dennis-Muse-Dangerfield-Sanders Non-Endowed Memorial Scholarship T he Oluremi Sano Award for Excellence in English Perry E. Thompson Scholarship Mrs. Pinkie Robertson Scholarship NEVCO Sports, LLC Scholarship Pinkie Robertson, Jennie V. Wilson and Dr. Lucy McIntosh Non-Endowed Scholarship Radiothon Scholarship The Road to Success Scholarship Rosemary Ewing Scholarship Beasley Non-Endowed Scholarship Shermika Sade Bolden Non-Endowed Memorial Scholarship The Ward Robinson C’72 Finish Line Scholarship Zelma and Steve Moffett Scholarship ",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Nich",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "H Councill Trenholm State Technical College",
   "URL": "https://www.trenholmstate.edu/",
   "Majors": "Automotive & Transportation (TC, AS) Cosmetology (AC) Business Administration (AA, AS) Child & Human Development (AC) Culinary Arts & Hospitality (AA) Engineering Technologies (TC) General Education (AC, AA, AS) Graphic Design (AA)",
   "Degree": "Advance Short-Term Certificate (AC) Associate of Arts (AA) Associate of Science (AS) Technology Certificate (TC)",
   "City": "Montgomery",
   "State": "Alabama",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Nich",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Hampton University",
   "URL": "http://www.hamptonu.edu/",
   "Majors": "Accounting (BS) Applied Mathematics – Computational Mathematics (MS) Applied Mathematics – Nonlinear Science (MS) Applied Mathematics – Statistics & Probability (MS) Art (BA)  Atmospheric Science (MS, PhD) Aviation Management (BS, O-BS) Biblical Studies (O-AA) Biochemistry (BS) Biology (BS, MAT, MS) Biology - Environmental Science (MS) Broadcast Journalism (BA) Business Administration (BS, MBA, O-BS, O-PhD, PhD) Chemical Engineering (BS) Chemistry (BS, MS) Communicative Sciences and Disorders (BA, MA) Computer Engineering (BS) Computer Information Systems (BS) Computer Science (BS, MS) Counseling (EdS, MA, O-EdS, O-MA, PhD) Counselor Education and Supervision (O-PhD) Criminal Justice (BS, O-BS) Economic (BS) Education - Community Agency (MA)  Cybersecurity (O-MS) Educational Leadership (MA) Educational Management (O-PhD) Electrical Engineering (BS) Elementary Education (MA) English (BA) Entrepreneurship (BS) Finance (BS) Fine & Performing Arts (BA) Flight Education (BS)  Food Service Manager (CC) General Studies (O-AA, O-BA) Health, Physical Education, & Recreation (BS, MA) History (BA) Hotel & Resort Management (BS) Human Resource Management (O-Certificate) Information Assurance (O-MS) International Studies (BA) Liberal Studies (BA) Management (BS) Marketing (BS) Marine & Environmental System (BS) Mathematics (BS) Medical Science (MS) Music Education (BA, MAT) Music Performance (BA) Music Recording Technology (BS) Naval Science (BS)  Nursing (BS, LPN, MS, O-BS, O-MS, O-PhD) Paralegal Legal Studies (O-BA, O-Certificate) Pastoral Counseling (MA)  Physical Therapy (DPT) Physics (BS, MS, PhD) Planetary Science (MS, PhD) Political Science (BA) Print Journalism (BA) Psychology (BA, MS) Public Relations (BA) Religious (MA, MDiv) Religious Studies (O-AA, O-BA) School Counseling (MA) Sport Administration (MA) Secondary Biology (MAT) Secondary English (MAT) Secondary Mathematics (MAT) Secondary Music (MAT) Sociology (BA) Spanish (BA) Sports Administration (O-MS) Student Affairs, College Student Development (MA) Systems Organization and Management (BS) Theatre Art (BA)",
   "Degree": "Associate of Arts (AA) Associate of Science (AS) Bachelor of Science (BS) Career Certificate (CC) Doctor of Philosophy (PhD) Doctor of Physical Therapy (DPT) Educational Specialist (Ed.S) Masters of Art (MA) Master of Business (MBA) Master of Divinity (MDiv) Masters of Science (MS) Masters of Arts in Teaching (MAT) Online – AA Online – AS Online – BA Online – BS Online – Certificate Online – MA Online – MS Online - PhD",
   "City": "Hampton",
   "State": "Virginia",
   "Technology": "",
   "Financial Aid": "Iraq and Afghanistan Service Grant",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Nich",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Harris-Stowe State University",
   "URL": "http://go.hssu.edu/?CFID=5485760&CFTOKEN=29550137",
   "Majors": "Accounting (BS) Biology (BS) Business Administration (BS) Criminal Justice (BS) Early Childhood Education (BS)  Educational Studies (BS) Elementary Education (BS) Finance (BS) Health Care Management (BS) Information Sciences & Computer Technology (BS) Marketing (BS) Mathematics (BS) Middle School & Secondary Education (BS) Secondary Education (BS) Sociology (BS) Sustainability & Urban Ecology (BS) Urban Affairs (BS) Urban Agriculture (CC)",
   "Degree": "Bachelor of Science (BS) Career Certificate (CC)",
   "City": "St. Louis",
   "State": "Missouri",
   "Technology": "eLearning",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Nich",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Howard University",
   "URL": "https://www2.howard.edu/",
   "Majors": "Accounting (B.B.A.) African Studies (B.A., MA, PhD) Afro American Studies (B.A.) Anatomy (MS, PhD., MD/Ph.D.) Architecture (M.Arch.) Art History (B.A.) Art (B.F.A, MFA.) Atmospheric Sciences (MS, PhD) Biochemistry and Molecular Biology (MS, PhD, MD/PhD) Biology (BS, MS, PhD, MD/PhD) Business (M.B.A.) Clinical Laboratory Science (B.S.CLS.) Chemistry (B.S, MS,PhD, MD/PhD) Chemical Engineering (B.S., MS) Civil Engineering (B.S.CIV, M.Eng, PhD) Comm., Culture & Media Studies (Ph.D.) Communications - Speech Language Pathology 5-year Accelerated Master’s (M.S.) Comm. Sciences & Disorders (MS, PhD) Computer Engineering (B.S.Comp.Eng.) Computer Information Systems (B.B.A.) Computer Science (B.S., MSCS, PhD) Counseling Psychology (Ph.D.) Criminology (B.A.)  Dental Hygiene (Certificate) Dentistry (D.D.S.) Economics (B.A. MA, PhD) Education Leadership and Policy Studies (MEd, EdD) Educational Psychology (Ph.D.) Electrical Engineering (B.S.Elec.Eng., PhD) Elementary Education (B.S., MEd) English (B.A., MA, PhD) Executive MBA (E-M.B.A.) Film (M.F.A.) Finance (B.B.A.)  French (B.A.) Genetics & Human Genetics (MS, PhD, MD/PhD) Health Education (B.S.) Health Management (B.S.) Health Sciences (B.S.) Higher Education Leadership and Policy Studies (Ph.D.) History (B.A., MA, PhD) Human Development (B.S.) Human Performance (B.S.) Interdisciplinary Studies (B.A.) International Business (B.B.A.) Law (L.L.M, JD.), Leisure Studies (B.S.) Mathematics (B.S., MS, PhD) Management (B.B.A.) Marketing (B.B.A.) Mechanical Engineering (B.S.Mech.Eng., Meng, PhD) Media Journalism, Film and Communications (B.A.) Medicine (M.D.) Microbiology (PhD, MD/PhD) Music (B.M., MAM) Nutritional Sciences (B.S.) Nursing (BSN, MSN) Nutritional Sciences (M.S.) Occupational Therapy (MOT) Pharmaceutical Science (MS, PhD, MD/PhD) Pharmacy (Pharm.D.) Pharmacology (MS, Ph.D.) Philosophy (B.A.) Physical Therapy (D.P.T.) Physics (B.S.) Physics & Astronomy (MS, PhD)  Physiology & Biophysics (M.D/Ph.D.) Political Science (B.A., MA, PhD) Psychology (B.S, MS, PhD.) Physiology (PhD, MD/PhD) Public Health (MPH) Radiation Therapy (B.S.R.T.) Religion (MA, M.Div., M.Div./M.S.W., M.Div./M.B.A., D.Min) School Psychology (Ph.D.) School Psychology and Counseling Services (MEd) Secondary Education (MEd) Social Work (M.S.W., Ph.D.) Sociology (B.A.) Sociology and Criminology (MA, PhD) Spanish (B.A.) Strategic, Legal, & Management Communication (B.A.) Supply Chain Management (B.B.A.) Theatre Arts (B.F.A.)",
   "Degree": "Bachelor of Art (BA) Bachelors in Business Administration (BBA) Bachelor of Fine Art (BFA) Bachelor of Science (BS) Bachelor of Science in Clinical Laboratory Science (BSCLS) Bachelor in Nursing (BSN) Bachelor in Social Work (BSW) Certificate (PC) Doctor of Philosophy (PhD) Executive MBA (E-MBA) Masters of Architecture (MArch) Masters of Art (MA) Master of Business (MBA) Master of Divinity (MDiv) Masters of Education (MEd) Master of Fine Art (MFA) Master of Occupational Therapy (MOT) Masters of Science (MS) Master in Social Work (MSW) ",
   "City": "Washington",
   "State": "DC",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Huston-Tillotson University",
   "URL": "http://htu.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Austin",
   "State": "Texas",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Interdenominational Theological Center",
   "URL": "https://www.itc.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Atlanta",
   "State": "Georgia",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "J F Drake State Technical College",
   "URL": "http://www.drakestate.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Huntsville",
   "State": "Alabama",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Jackson State University",
   "URL": "http://www.jsums.edu/",
   "Majors": "Biology (BS/MS) Biomedical Science (BS) Chemistry (MS/PhD) Civil Engineering (BS) Computer Engineering (BS) Computer Science (BS/MS) Criminal Justice (BS) Education (BS/MS) Engineering (MS) English (BA/MA) Environmental Engineering (BS) Environmental Science (BS/MS/PhD) Foreign Language (BA) Forensic Science (BS) Hazardous Materials Management (MS) History (BA/BS/MA) Integrated Marketing (BS/MS) Mathematics (BS) Media Production (BS) Meteorology (BS) Multimedia Journalism (BS/MS) Music Education (BME) Physics (BS) Political Science (BA/MA) Pure and Applied Mathematics (MS) Psychology (BS/PhD) Speech (BA) Sociology (BA/MA) Teaching (MAT) Telecommunications Engineering (BS)Theatre (BA)",
   "Degree": "Bachelor of Arts (BA) Bachelor of Business Administration (BBA) Bachelor of Science (BS) Bachelor of Music (BM) Master of Art (MA) Master of Arts in Teaching (MAT)",
   "City": "Jackson",
   "State": "Mississippi",
   "Technology": "Canvas KACE PAWS",
   "Financial Aid": "Academic Scholarships Alumni Scholarships Apple HBCU Scholars Program Civil Engineering Scholarship Development Scholarship First Time Freshman Scholarship Graduate Diversity Scholarship Latino Scholarship STEM/Women and Minorities Scholarships",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Jarvis Christian College",
   "URL": "https://www.jarvis.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Hawkins",
   "State": "Texas",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Johnson C Smith University",
   "URL": "https://www.jcsu.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Charlotte",
   "State": "North Carolina",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Kentucky State University",
   "URL": "https://kysu.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Frankfort",
   "State": "Kentucky",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Lane College",
   "URL": "https://www.lanecollege.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Jackson",
   "State": "Tennessee",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Langston University",
   "URL": "https://www.langston.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Langston",
   "State": "Oklahoma",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Lawson State Community College-Birmingham Campus",
   "URL": "http://www.lawsonstate.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Birmingham",
   "State": "Alabama",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Le Moyne-Owen College",
   "URL": "http://www.loc.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Memphis",
   "State": "Tennessee",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Lincoln University",
   "URL": "https://www.lincolnu.edu/pages/1.asp",
   "Majors": "",
   "Degree": "",
   "City": "Jefferson City",
   "State": "Missouri",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Lincoln University of Pennsylvania",
   "URL": "http://www.lincoln.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Philadelphia",
   "State": "Pennsylvania",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Livingstone College",
   "URL": "http://livingstone.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Salisbury",
   "State": "North Carolina",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Meharry Medical College",
   "URL": "http://www.mmc.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Nashville",
   "State": "Tennessee",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Miles College",
   "URL": "http://www.miles.edu/",
   "Majors": "Biology (BS) Computer Information Sciences (BS) Environmental Sciences (BS) Management Information Systems (BS) Mathematics (BS) Chemistry (BS)",
   "Degree": "Bachelors of Science (BS)",
   "City": "Fairfield",
   "State": "Alabama",
   "Technology": "BlackBoard",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Mississippi Valley State University",
   "URL": "http://www.mvsu.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Itta Bena",
   "State": "Mississippi",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Morehouse College",
   "URL": "http://www.morehouse.edu/",
   "Majors": "African American Studies  (BA) Biology (BS) Business Administration (BA) Chemistry (BS) Chinese Studies (BA) Cinema Television & Emerging Media Studies (BA) Computer Science (BS) Economics (BA) English (BA) History (BA) Kinesiology, Sports Studies & Physical Education (BA) Mathematics (BS) Modern Foreign Languages  (BA) Music (BA) Philosophy & Religion  (BA) Political Science  (BA) Psychology (BS) Sociology (BA) Survey of Visual Arts  (BA) Urban Studies  (BA)",
   "Degree": "BS BA",
   "City": "Atlanta",
   "State": "Georgia",
   "Technology": "Banner 8 ",
   "Financial Aid": "HOPE",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Morehouse School of Medicine",
   "URL": "http://www.msm.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Atlanta",
   "State": "Georgia",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Morgan State University",
   "URL": "https://www.morgan.edu/",
   "Majors": "Advanced Computing (MS) Biology (BS) Chemistry (BS) Computer Science (BS) English (BA) Engineering (BS/MEng) Finance (BA) Mathematics (BS/MA) Nursing (BA/MS) Science (MS)",
   "Degree": "Bachelors of Arts (BA) Bachelor of Science (BS) Master of Arts (MA) Master of Science (MS)",
   "City": "Baltimore",
   "State": "Maryland",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Morris College",
   "URL": "http://www.morris.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Sumter",
   "State": "South Carolina",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Norfolk State University",
   "URL": "http://www.nsu.edu/",
   "Majors": "Accountancy (BS) Architectural Drafting (AS) Biology (BS) Chemistry (BS) Computer Engineering Technology (BS) Computer Science (BS/MS) Construction Management Engineering Technology (BS) Criminal Justice (MA) Cybersecurity (MS) Electrical and Electronics Engineering (BS) Electronics Engineering (MS) Mathematics (BS) Nursing (BS) History (BA) Physics (BS) Social Work (BSW)",
   "Degree": "Associates of Science (AS) Bachelors in Science (BS)' Bachelor of Social Work (BSW) Masters of Arts (MA)",
   "City": "Norfolk",
   "State": "Virginia",
   "Technology": "Blackboard Learning Management System (LMS) Pearson ReadSpeaker SmartThinking SoftChalk Virtual Computing Labs",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "North Carolina A & T State University",
   "URL": "http://www.ncat.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Greensboro",
   "State": "North Carolina",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "North Carolina Central University",
   "URL": "http://www.nccu.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Durham",
   "State": "North Carolina",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Oakwood University",
   "URL": "http://www.oakwood.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Huntsville",
   "State": "Alabama",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Paine College",
   "URL": "https://www.paine.edu/web/mycampus/home",
   "Majors": "",
   "Degree": "",
   "City": "Augusta",
   "State": "Georgia",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Paul Quinn College",
   "URL": "http://www.pqc.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Dallas",
   "State": "Texas",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Philander Smith College",
   "URL": "https://www.philander.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Little Rock",
   "State": "Arkansas",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Prairie View A & M University",
   "URL": "https://www.pvamu.edu/",
   "Majors": "Applied Mathematics (BS) Biology (BS) Chemistry (BS, MS) Communication (BA) English (BA) Mathematics Teaching (BS) Physics (BS) Statistics (BS)",
   "Degree": "Bachelors of Arts (BA) Bachelor of Science (BS)",
   "City": "Prairie View",
   "State": "Texas",
   "Technology": "Baner WebX Zoom",
   "Financial Aid": "ASNT Engineering Undergraduate Scholarship Ashley College Tour Scholarship Program National Founder’s Undergraduate Business Student Scholarship National Founder’s Undergraduate Business Student Scholarship Veteran Car Donations Annual Scholarship Michael Moody Fitness Scholarship ",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Rust College",
   "URL": "http://www.rustcollege.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Holly Springs",
   "State": "Mississippi",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Saint Augustines College",
   "URL": "https://www.st-aug.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Raleigh",
   "State": "North Carolina",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Saint Pauls College",
   "URL": "https://www.saintpaul.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Brooklandville",
   "State": "Maryland",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Savannah State University",
   "URL": "https://www.savannahstate.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Savannah",
   "State": "Georgia",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Selma University",
   "URL": "https://www.selmauniversity.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Selma",
   "State": "Alabama",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Shaw University",
   "URL": "http://www.shawu.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Raleigh",
   "State": "North Carolina",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Shelton State Community College",
   "URL": "https://www.sheltonstate.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Tuscaloosa",
   "State": "Alabama",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "South Carolina State University",
   "URL": "http://www.scsu.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Orangeburg",
   "State": "South Carolina",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Southern University and A & M College",
   "URL": "http://www.subr.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Baton Rouge",
   "State": "Louisiana",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Southern University at New Orleans",
   "URL": "http://www.suno.edu/",
   "Majors": "",
   "Degree": "",
   "City": "New Orleans",
   "State": "Louisiana",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Southern University at Shreveport",
   "URL": "http://www.susla.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Shreveport",
   "State": "Louisiana",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Southwestern Christian College",
   "URL": "http://www.swcc.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Terrell",
   "State": "Texas",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Spelman College",
   "URL": "http://www.spelman.edu/",
   "Majors": "Art Art History Biochemistry  Biology Chemistry Comparative Women's Studies Computer and Information Sciences Dance Performance & Choreography  Documentary Filmmaking Early Childhood Education Economics Education Studies English Environmental Sciences Environmental Studies French General Science (Dual Degree Engineering) Health Sciences   History Human Services Independent Major International Studies Mathematics Music Philosophy Photography Physics Political Science Psychology Religious Studies Spanish Sociology Sociology and Anthropology Theatre & Performance",
   "Degree": "Bachelors of Arts (BA) Bachelors of Science (BS)",
   "City": "Atlanta",
   "State": "Georgia",
   "Technology": "Moodle, Purdue SpelApps Zoom",
   "Financial Aid": "Bonner Scholarship Dean’s Scholarship Dean’s Academic Scholarship Flanigan Scholarship Presidential Scholarship Student of Distinction",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "St Philips College",
   "URL": "http://www.alamo.edu/spc/",
   "Majors": "",
   "Degree": "",
   "City": "San Antonio",
   "State": "Texas",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Stillman College",
   "URL": "http://stillman.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Tuscaloosa",
   "State": "Alabama",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Talladega College",
   "URL": "http://talladega.brinkster.net/joomla25/index.php",
   "Majors": "",
   "Degree": "",
   "City": "Talladega",
   "State": "Alabama",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Tennessee State University",
   "URL": "http://www.tnstate.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Nashville",
   "State": "Tennessee",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Texas College",
   "URL": "https://www.texascollege.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Tyler",
   "State": "Texas",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Texas Southern University",
   "URL": "http://www.tsu.edu/home/",
   "Majors": "",
   "Degree": "",
   "City": "Houston",
   "State": "Texas",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Tougaloo College",
   "URL": "https://www.tougaloo.edu/",
   "Majors": "Biology (BS) Biology (BS) Chemistry (BS) Chemistry Education (BS) Computer Science (BS) Mathematics (BS) Mathematics Education (BS) Physics (BS)",
   "Degree": "",
   "City": "Jackson",
   "State": "Mississippi",
   "Technology": "Moodle",
   "Financial Aid": "Athletic Scholarships Community College Graduate Academic  Critical Needs Teacher Loan/Scholarship Freshman Academic Music Scholarships Presidential Academic Provost Academic Servant Leader Academic Phi Theta Kappa ",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Tuskegee University",
   "URL": "https://www.tuskegee.edu/",
   "Majors": "Accounting (BS) Aerospace Science Engineering (BS) Agribusiness (BS) Agricultural & Resource Economics* (MS) Animal, Poultry and Veterinary Sciences (BS) Animal Sciences (MS) Architecture (A.Arch) Biology (BS, MS) Business Administration (BS) Chemical Engineering (BS, MS) Chemistry (BS, MS) Clinical Laboratory Science (BS) Computer Engineering (BS) Computer Science (BS) Communications (BA) Construction Science and Management (BS) Economics (BS) Electrical Engineering (BS, MS) Elementary Education (BA) English (BA) English Language Arts Education (BA) Environmental (BS) Environmental Management (O-MS) Environmental Science (MS, O-MS) Natural Resource and Plant Sciences Finance (BS) Food and Nutritional Sciences (BS, MS) General Psychology (MS) General Science Education (BA) General Science Education (BA) Hospitality Management (BA) Information Systems & Security Mgt (MS) Information Technology (BS) Integrative Biosciences (PhD) Integrative Public Policy & Development (PhD) Interdisciplinary Pathobiology (PhD) Management Science (BS) Materials Science & Engineering (MS, PhD) Mathematics (BA) Mathematics Education (BA) Mechanical Engineering (BS, MS) Music (BA) Nursing (BS) Occupational Therapy (BS, MS) Plant & Soil Sciences(MS) Physical Education(BA) Physics (BS) Political Science (BA) Psychology (BA) Public Health (MS) Public Health Nutrition (BS) Sales and Marketing (BS) Social Work (BA) Sociology (BA) Supply Chain Management (BS) Veterinary Sciences (MS) Visual Arts (BA) ",
   "Degree": "Bachelor of Architecture (B. Arch) Bachelor of Arts (BA), Bachelor of Science (BS), Doctor of Philosophy (PhD), Masters of Science (MS), Online – MS, ",
   "City": "Tuskegee",
   "State": "Alabama",
   "Technology": "Blackboard",
   "Financial Aid": "Athletic Scholarships, ChameleonJohn Scholarship, Computer Science Scholars Program, External Scholarships, Freshman Scholarships, R.O.T.C. Scholarships, Shomari Asim Foster Scholarship, Transfer Student Scholarships  ",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "https://tuskegee.university-tour.com/map.php",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "University of Arkansas at Pine Bluff",
   "URL": "http://www.uapb.edu/",
   "Majors": "Art (BS), Biochemistry (BS), Biology (BS), Chemistry (BS), Chemistry Education (BS), Computer Science Information Systems (BS), Computer Science-Math (BS), Criminal Justice (BA), Forensic Chemistry (BS), Gerontology (BA), History (BA), Industrial Technology, Management & Applied Engineering (BS), Mathematics (BS), Nursing (BS), Physics (BS), Psychology (BS), Social Work (BA), Social Sciences Education (BA), Sociology (BA)",
   "Degree": "Bachelors of Arts (BA), Bachelor of Science (BS),",
   "City": "Pine Bluff",
   "State": "Arkansas",
   "Technology": "BlackBoard",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "University of Maryland Eastern Shore",
   "URL": "https://www.umes.edu/home/",
   "Majors": "",
   "Degree": "",
   "City": "Princess Anne",
   "State": "Maryland",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "University of the District of Columbia",
   "URL": "https://www.udc.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Washington",
   "State": "DC",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "University of the Virgin Islands",
   "URL": "https://www.uvi.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Charlotte Amalie West",
   "State": "St Thomas",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Virginia State University",
   "URL": "http://www.vsu.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Petersburg",
   "State": "Virginia",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Virginia Union University",
   "URL": "https://www.vuu.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Richmond",
   "State": "Virginia",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Virginia University of Lynchburg",
   "URL": "http://www.vul.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Lynchburg",
   "State": "Virginia",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Voorhees College",
   "URL": "https://www.voorhees.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Denmark",
   "State": "South Carolina",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "West Virginia State University",
   "URL": "http://www.wvstateu.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Institute",
   "State": "West Virginia",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Wilberforce University",
   "URL": "http://wilberforce.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Wilberforce",
   "State": "Ohio",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Wiley College",
   "URL": "http://www.wileyc.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Marshall",
   "State": "Texas",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Winston-Salem State University",
   "URL": "https://www.wssu.edu/",
   "Majors": "",
   "Degree": "",
   "City": "Winston-Salem",
   "State": "North Carolina",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 },
 {
   "Schools": "Xavier University of Louisiana",
   "URL": "http://www.xula.edu/",
   "Majors": "",
   "Degree": "",
   "City": "New Orleans",
   "State": "Louisiana",
   "Technology": "",
   "Financial Aid": "",
   "Logo": "",
   "Campus Image": "",
   "Assigned": "Chris",
   "Virtual Tour": "",
   "Graduates": "",
   "Notes": ""
 }
]