# Generated by Django 3.0.8 on 2020-07-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('logo', models.TextField(blank=True, null=True)),
            ],
            options={
                'order_with_respect_to': 'name',
            },
        ),
    ]
