# Generated by Django 3.0.8 on 2020-08-06 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majors', models.TextField(max_length=200, null=True)),
                ('states', models.TextField(max_length=200, null=True)),
                ('technology', models.TextField(max_length=200, null=True)),
                ('financialaid', models.TextField(max_length=200, null=True)),
                ('category', models.TextField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.TextField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hbcu.Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=255, null=True)),
                ('firstname', models.TextField(max_length=255, null=True)),
                ('lastname', models.TextField(max_length=255, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, max_length=255, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'order_with_respect_to': 'lastname',
            },
        ),
        migrations.CreateModel(
            name='HBCUgrads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='', max_length=3000)),
                ('last_name', models.TextField(default='', max_length=3000)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('career', models.TextField(default='', max_length=3000)),
                ('date_born', models.TextField(default='', max_length=3000)),
                ('date_died', models.TextField(default='', max_length=3000)),
                ('school', models.TextField(default='', max_length=3000)),
                ('image', models.TextField(blank=True, null=True)),
                ('history', models.TextField(default='', max_length=3000)),
            ],
            options={
                'order_with_respect_to': 'last_name',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=3000)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('major', models.TextField(default='', max_length=3000)),
                ('degree', models.TextField(default='', max_length=3000)),
                ('city', models.TextField(default='', max_length=3000)),
                ('state', models.TextField(default='', max_length=3000)),
                ('technology', models.TextField(default='', max_length=500)),
                ('financial_aid', models.TextField(default='', max_length=3000)),
                ('logo', models.TextField(blank=True, null=True)),
                ('campus_image', models.TextField(blank=True, null=True)),
                ('virtual_tour', models.TextField(default='', max_length=3000)),
                ('history', models.TextField(default='', max_length=3000)),
            ],
            options={
                'order_with_respect_to': 'name',
            },
        ),
    ]
