# Generated by Django 3.0.8 on 2020-08-12 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.TextField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HBCUgrads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=3000)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('career', models.TextField(default='', max_length=3000)),
                ('date_born', models.TextField(default='', max_length=3000)),
                ('date_died', models.TextField(default='', max_length=3000)),
                ('school', models.TextField(default='', max_length=3000)),
                ('image', models.TextField(blank=True, null=True)),
                ('history', models.TextField(default='', max_length=3000)),
            ],
            options={
                'order_with_respect_to': 'name',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=3000)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('city', models.TextField(default='', max_length=3000)),
                ('state', models.TextField(blank=True, null=True)),
                ('technology', models.TextField(default='', max_length=500)),
                ('financial_aid', models.TextField(default='', max_length=3000)),
                ('logo', models.TextField(blank=True, null=True)),
                ('campus_image', models.TextField(blank=True, null=True)),
                ('virtual_tour', models.BooleanField(default=False)),
                ('history', models.TextField(default='', max_length=3000)),
                ('degree', models.ManyToManyField(to='hbcu.Degree')),
                ('major', models.ManyToManyField(to='hbcu.Major')),
            ],
            options={
                'order_with_respect_to': 'name',
            },
        ),
    ]
