# Generated by Django 3.0.8 on 2020-08-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hbcugrads',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AlterOrderWithRespectTo(
            name='hbcugrads',
            order_with_respect_to='name',
        ),
        migrations.RemoveField(
            model_name='hbcugrads',
            name='last_name',
        ),
    ]
