# Generated by Django 3.0.8 on 2020-07-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
