# Generated by Django 3.0.8 on 2020-08-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
