# Generated by Django 3.0.8 on 2020-08-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0002_auto_20200812_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(max_length=3000),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
