# Generated by Django 3.0.8 on 2020-08-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0002_auto_20200809_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='virtual_tour',
            field=models.BooleanField(default=False),
        ),
    ]
