# Generated by Django 3.0.8 on 2020-08-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0002_auto_20200811_0719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
