# Generated by Django 3.0.8 on 2020-08-12 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0003_auto_20200812_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hbcu.State'),
        ),
    ]
