# Generated by Django 3.0.8 on 2020-08-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0003_auto_20200812_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='name',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.RemoveField(
            model_name='college',
            name='major',
        ),
        migrations.AddField(
            model_name='college',
            name='major',
            field=models.ManyToManyField(to='hbcu.Major'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='major',
            order_with_respect_to=None,
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='major',
            name='city',
        ),
        migrations.RemoveField(
            model_name='major',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='major',
            name='email',
        ),
        migrations.RemoveField(
            model_name='major',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='major',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='major',
            name='state',
        ),
        migrations.RemoveField(
            model_name='major',
            name='username',
        ),
    ]
