# Generated by Django 3.0.8 on 2020-08-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0004_auto_20200812_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='state',
        ),
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.ManyToManyField(to='hbcu.State'),
        ),
    ]
