# Generated by Django 3.0.8 on 2020-08-12 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0004_auto_20200812_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.RemoveField(
            model_name='college',
            name='degree',
        ),
        migrations.AddField(
            model_name='college',
            name='degree',
            field=models.ManyToManyField(to='hbcu.Degree'),
        ),
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hbcu.State'),
        ),
    ]
