# Generated by Django 3.0.8 on 2020-08-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0005_auto_20200812_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='state',
        ),
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
