# Generated by Django 3.0.8 on 2020-08-12 02:21

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0005_auto_20200812_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
    ]
