# Generated by Django 3.0.8 on 2020-08-03 05:38

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0006_auto_20200802_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='campus_image',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='college',
            name='degree',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='financial_aid',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='major',
            field=models.CharField(default='', max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='college',
            name='technology',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='college',
            name='virtual_tour',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
