# Generated by Django 3.0.8 on 2020-08-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0006_auto_20200812_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=3000)),
            ],
        ),
        migrations.RemoveField(
            model_name='college',
            name='state',
        ),
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.ManyToManyField(to='hbcu.State'),
        ),
    ]
