# Generated by Django 3.0.8 on 2020-08-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0007_auto_20200812_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='degree',
            new_name='degrees',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='major',
            new_name='majors',
        ),
        migrations.RemoveField(
            model_name='college',
            name='state',
        ),
    ]
