# Generated by Django 3.0.8 on 2020-08-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0007_auto_20200803_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='campus_image',
            field=models.ImageField(blank=True, default='', max_length=3000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='college',
            name='city',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='college',
            name='degree',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='college',
            name='financial_aid',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(blank=True, default='', max_length=3000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='college',
            name='major',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='college',
            name='virtual_tour',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='major',
            name='city',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='firstname',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='lastname',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='username',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
