# Generated by Django 3.0.8 on 2020-08-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0008_auto_20200812_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='states',
            field=models.ManyToManyField(to='hbcu.State'),
        ),
    ]
