# Generated by Django 3.0.8 on 2020-08-12 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0009_college_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='states',
        ),
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='hbcu.State'),
        ),
    ]
