# Generated by Django 3.0.8 on 2020-08-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0009_auto_20200803_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='history',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
