# Generated by Django 3.0.8 on 2020-08-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0010_auto_20200812_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='virtual_tour',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
