# Generated by Django 3.0.8 on 2020-08-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0012_auto_20200805_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='city',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='college',
            name='degree',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='college',
            name='financial_aid',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='college',
            name='history',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='college',
            name='major',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='college',
            name='technology',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='college',
            name='virtual_tour',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='major',
            name='city',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='firstname',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='lastname',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='username',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='financialaid',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='majors',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='states',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='technology',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
