# Generated by Django 3.0.8 on 2020-08-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbcu', '0013_auto_20200805_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='HBCUgrads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='', max_length=3000)),
                ('last_name', models.TextField(default='', max_length=3000)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('career', models.TextField(default='', max_length=3000)),
                ('date_born', models.TextField(default='', max_length=3000)),
                ('date_died', models.TextField(default='', max_length=3000)),
                ('school', models.TextField(default='', max_length=3000)),
                ('image', models.TextField(blank=True, null=True)),
                ('history', models.TextField(default='', max_length=3000)),
            ],
            options={
                'order_with_respect_to': 'last_name',
            },
        ),
    ]
